# Generated by Django 5.0.14 on 2025-06-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('nguoidung_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('tennguoidung', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tenNguoiDung', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('matkhau', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='matKhau', max_length=100, null=True)),
                ('dienthoai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='dienThoai', max_length=100, null=True)),
                ('vaitro', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='vaiTro', max_length=10, null=True)),
                ('ngaytaotk', models.DateField(blank=True, db_column='ngayTaoTK', null=True)),
            ],
            options={
                'db_table': 'NguoiDung',
            },
        ),
    ]
