# Generated by Django 5.0.14 on 2025-06-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('thanhtoan_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('sothe', models.CharField(blank=True, max_length=16, null=True)),
                ('ngayhethan', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('ngaythanhtoan', models.DateTimeField(auto_now_add=True)),
                ('trangthai', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('dondatphong', models.ForeignKey(db_column='DonDatPhong_lichsu_id', on_delete=django.db.models.deletion.CASCADE, to='rooms.dondatphong')),
            ],
            options={
                'db_table': 'ThanhToan',
            },
        ),
    ]
