# Generated by Django 5.0.14 on 2025-06-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diadiem',
            fields=[
                ('diadiem_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('tendiadiem', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tenDiaDiem', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DiaDiem',
            },
        ),
        migrations.CreateModel(
            name='Khachsan',
            fields=[
                ('khachsan_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('tenkhachsan', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tenKhachSan', max_length=200, null=True)),
                ('mota', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='moTa', max_length=1000, null=True)),
                ('ngaythem', models.DateField(blank=True, db_column='ngayThem', null=True)),
            ],
            options={
                'db_table': 'KhachSan',
            },
        ),
        migrations.CreateModel(
            name='Loaiphong',
            fields=[
                ('phong_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('tenphong', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tenPhong', max_length=100, null=True)),
                ('sogiuong', models.IntegerField(blank=True, db_column='soGiuong', null=True)),
                ('gia', models.FloatField(blank=True, null=True)),
                ('mota', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='moTa', max_length=1000, null=True)),
                ('ngaythemphong', models.DateField(blank=True, db_column='ngayThemPhong', null=True)),
                ('khachsankhachsan', models.ForeignKey(blank=True, db_column='KhachSankhachsan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.khachsan')),
            ],
            options={
                'db_table': 'LoaiPhong',
            },
        ),
        migrations.CreateModel(
            name='Hinhanh',
            fields=[
                ('anh_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('urlhinhanh', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='urlHinhAnh', max_length=100, null=True)),
                ('phongphong', models.ForeignKey(blank=True, db_column='Phongphong_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.loaiphong')),
            ],
            options={
                'db_table': 'HinhAnh',
            },
        ),
        migrations.CreateModel(
            name='Dondatphong',
            fields=[
                ('lichsu_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('ngaydat', models.DateField(blank=True, db_column='ngayDat', null=True)),
                ('ngaytra', models.DateField(blank=True, db_column='ngayTra', null=True)),
                ('tongtien', models.FloatField(blank=True, db_column='tongTien', null=True)),
                ('trangthai', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='trangThai', max_length=20, null=True)),
                ('thoigiandat', models.DateField(blank=True, db_column='thoiGianDat', null=True)),
                ('nguoidungnguoidung', models.ForeignKey(blank=True, db_column='NguoiDungnguoidung_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.nguoidung')),
                ('phongphong', models.ForeignKey(blank=True, db_column='Phongphong_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.loaiphong')),
            ],
            options={
                'db_table': 'DonDatPhong',
            },
        ),
        migrations.CreateModel(
            name='Quanhuyen',
            fields=[
                ('quanhuyen_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, primary_key=True, serialize=False)),
                ('tenquanhuyen', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tenQuanHuyen', max_length=100, null=True)),
                ('diadiemdiadiem', models.ForeignKey(blank=True, db_column='DiaDiemdiadiem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.diadiem')),
            ],
            options={
                'db_table': 'QuanHuyen',
            },
        ),
        migrations.AddField(
            model_name='khachsan',
            name='quanhuyenquanhuyen',
            field=models.ForeignKey(blank=True, db_column='QuanHuyenquanhuyen_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.quanhuyen'),
        ),
    ]
